### ISSUE TITLE
Not compatible with Flutter 1.17.5

### ISSUE THREAD

**Issue by Dinesh41** [chooyan-eng/crop_your_image#29]
I need to use this plugin in Flutter 1.17.5.

If i upgrade to Flutter latest version and add this plugin. Version solving is failing due to other dependencies.

**Comment by chooyan-eng** [comment]
@Dinesh41 Thank you for your feedback. I’ll check this.

**Comment by chooyan-eng** [comment]
@Dinesh41 
I have to inform you that this package uses dart 2.12.0 or above for Null Safety, and Flutter 2.0 is required to be installed into your PC.

If you have other dependency which is not available with Flutter 2.0  in your project, it means there is no way for me to solve the issue other than waiting for those packages applied to Null Safety as well.

Or, you can folk this project and rewrite the code in this package without Null Safety.

**Comment by searchy2** [comment]
I needed the library non-null safe too.
I converted it in my fork https://github.com/searchy2/crop_your_image/tree/ray-nonnullsafe

Include it in your project with Git import: 
```
  crop_your_image:
    git:
      url: git://github.com/searchy2/crop_your_image.git
      ref: ray-nonnullsafe
```
